version: '2'

# Development docker-compose file for the Dialogue and Argumentation Framework
# Mounts source code as volumes to allow for easier testing

services:
 #internal activemq service for communication between modules
 activemq_internal:
  image: webcenter/activemq:latest
  container_name: activemq-internal
  ports:
  - "8162:8161"

 #external activemq service for outside communication
 activemq_external:
  image: webcenter/activemq:latest
  container_name: activemq-external
  ports:
  - "8161:8161"
  - "61613:61613"
  - "61616:61616"
  - "61614:61614"

 #controller to map external to internal amq topics
 controller:
   build: ./daf-controller
   container_name: daf_controller
   volumes:
   - ./daf-controller/app:/app
   depends_on:
   - activemq_internal
   - activemq_external
   environment:
   - INTERNAL_AMQ_HOST=activemq-internal
   - EXTERNAL_AMQ_HOST=activemq-external

 #dgep
 dgep:
  build: ./dgep
  container_name: dgep
  volumes:
  - ./dgep/src:/dgep/src

 #filstantiator
 utterance_generator:
  build: ./utterance_generator
  container_name: utterance_generator
  depends_on:
  - dung_o_matic
  volumes:
  - ./utterance_generator/src:/app
  env_file:
  - ./utterance_generator/config.env

 # #toast: required by utterance_generator
 # toast:
 #  build: ./toast
 #  container_name: toast
 #  ports:
 #    - "1234:1234"

 #dung-o-matic: required by utterance_generator
 dung_o_matic:
   build: ./dung-o-matic
   container_name: dungomatic
   ports:
     - "8000:80"

 #mongodb: required by utterance_generator
 mongodb:
  image: mongo
  volumes:
  - ./mongo/data/db:/data/db
  ports:
  - "27017:27017"
  container_name: mongodb

 #web-based demonstrator for the daf
 dafdemo:
  build: ./daf-demonstrator
  volumes:
  - ./daf-demonstrator/www:/var/www/html
  ports:
  - "8080:80"
