version: '3'

# Core docker-compose file for the Dialogue and Argumentation Framework

services:
 # external activemq service for outside communication
 activemq_external:
  image: webcenter/activemq:latest
  container_name: activemq-external
  ports:
  - "8161:8161"
  - "61613:61613"
  - "61616:61616"
  - "61614:61614"

 daf:
  build: ./daf-core
  container_name: daf_core
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock

# networks:
#   default:
#     external:
#       name: daf-network
